services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${WEB_PORT_HOST}:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/web:/app/apps/web
      - /app/node_modules
    command: pnpm exec next dev -H 0.0.0.0
    depends_on:
      - api

  api:
    build: ./apps/api
    ports:
      - "${API_PORT_HOST}:2000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/chamber
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    command: pnpm run start:dev
    depends_on:
      - db

  ai:
    build: ./apps/ai
    ports:
      - "${AI_PORT_HOST}:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./apps/ai:/app
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8000


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chamber
    ports:
      - "${DB_PORT_HOST}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "${REDIS_PORT_HOST}:6379"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@chamber.fm
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "${PGADMIN_PORT_HOST}:80"
    depends_on:
      - db

  studio:
    build:
      context: ./apps/api
    command: npx prisma studio --port 5050
    ports:
      - "${STUDIO_PORT_HOST}:5050"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/chamber
    depends_on:
      - db

volumes:
  pgdata:
