services:
  web:
    build: ./apps/web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    command: pnpm run dev
    depends_on:
      - api

  api:
    build: ./apps/api
    ports:
      - "2000:2000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/chamber
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    command: pnpm run start:dev
    depends_on:
      - db

  ai:
    build: ./apps/ai
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./apps/ai:/app
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8000


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chamber
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@chamber.fm
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5051:80" # Changed to avoid conflict with Postgres
    depends_on:
      - db

  studio:
    build:
      context: ./apps/api
    command: npx prisma studio --port 5050
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/chamber
    depends_on:
      - db

volumes:
  pgdata:
